/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: {
            parameters: {
                query?: {
                    /** @example pending */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns empty array when no tasks exist */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example [] */
                        "application/json": {
                            id: number;
                            title: string;
                            description: string | null;
                            status: string;
                            created_at: string;
                            updated_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "task": {
                     *         "title": "進行中タスク",
                     *         "description": "メモ",
                     *         "status": "in_progress"
                     *       }
                     *     }
                     */
                    "application/json": {
                        task: {
                            title: string;
                            description?: string;
                            status?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a task with status */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 1,
                         *       "title": "進行中タスク",
                         *       "description": null,
                         *       "status": "in_progress",
                         *       "created_at": "2026-05-26T23:11:05.368Z",
                         *       "updated_at": "2026-05-26T23:11:05.368Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            title: string;
                            description: string | null;
                            status: string;
                            created_at: string;
                            updated_at: string;
                        };
                    };
                };
                /** @description returns 422 for invalid status */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": [
                         *         "Status is not included in the list"
                         *       ]
                         *     }
                         */
                        "application/json": {
                            errors: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 999999 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns a task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 1,
                         *       "title": "テスト",
                         *       "description": "メモ",
                         *       "status": "in_progress",
                         *       "created_at": "2026-05-26T23:11:05.317Z",
                         *       "updated_at": "2026-05-26T23:11:05.317Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            title: string;
                            description: string;
                            status: string;
                            created_at: string;
                            updated_at: string;
                        };
                    };
                };
                /** @description returns 404 for not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Task not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** destroy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 999999 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletes a task */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description returns 404 for not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Task not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 999999 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "task": {
                     *         "title": "更新後",
                     *         "status": "in_progress"
                     *       }
                     *     }
                     */
                    "application/json": {
                        task: {
                            title: string;
                            status: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updates a task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "title": "更新後",
                         *       "status": "in_progress",
                         *       "id": 1,
                         *       "description": null,
                         *       "created_at": "2026-05-26T23:11:05.438Z",
                         *       "updated_at": "2026-05-26T23:11:05.451Z"
                         *     }
                         */
                        "application/json": {
                            title: string;
                            status: string;
                            id: number;
                            description: unknown;
                            created_at: string;
                            updated_at: string;
                        };
                    };
                };
                /** @description returns 404 for not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Task not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid update */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": [
                         *         "Title can't be blank"
                         *       ]
                         *     }
                         */
                        "application/json": {
                            errors: string[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
